### ISSUE TITLE
Thank you for sharing (2) ⭐️

### ISSUE THREAD

**Issue by oieduardorabelo** [malaval/aws-orga-deployer#4]
Extending the "thank you" from https://github.com/malaval/aws-orga-deployer/issues/1, fantastic project @malaval!

Picking up what you said in that other thread: "...AWS Orga Deployer is not made to manage AWS Organizations..."

Does that mean you handle it in a different project/tool? I assume Terraform?

I was doing research / POC the last few days on the scenario: 

```
I have a brand new AWS account, 
Signup is completed, and I just created my first IAM User with Admin permissions. 
Now what?
```

That's how I landed here =)

It's fair to assume that to enable AWS Organizations, create OUs, AWS accounts, Identity Center/SSO mappings/Permission sets, SCPs, etc.; I should use a different tool, and AWS Orga Deployer would come after this stage to baseline the accounts?

**Comment by malaval** [comment]
Thanks for sharing feedback :-)

By "AWS Orga Deployer is not made to manage AWS Organizations", I meant that it is not the best tool to create your AWS accounts programmatically, like orgformation or a classical "account vending machine" would do, because it doesn't bring additional value that pure Terraform or CloudFormation.

One of the AWS Orga Deployer "limitations" is that the deployments to create are evaluated at the beginning of an execution, so if one of the deployment consists of creating an account, it won't be able to deploy resources in that account during the same execution, because that account didn't exist yet at the time it evaluated the deployments to create. But you could split that in two packages executed sequentially for example (see below).

In my current company, we "enable AWS Organizations, create OUs, AWS accounts, Identity Center/SSO mappings/Permission sets, SCPs" manually given the small size of our organization and then we use AWS Orga Deployer (I know it is quite bad coming from someone advocating infra-as-code and automation :-).

But if you are able to create organization resources it with Terraform, there is no reason you could not it with AWS Orga Deployer (it is just a multi-account-region wrapper). So you could imagine a pipeline of two sequential AWS Orga Deployer packages:

- one package to create AWS accounts, create OUs, etc. But this package would typically be a single Terraform/CloudFormation module that creates the resources, and the benefit of AWS Orga Deployer is low here.

- another package executed after the first one to create account resources by assuming the IAM role created by AWS Organizations (the one provided as argument in the CreateAccount). You don't have to edit the "package.yaml" file if the deployments target all accounts in the organization or given OUs. For example, if you want to deploy a specific IAM role in all accounts in the "prod" OU, you just need to specify a deployment once in your "package.yaml". If you create a new account matching these conditions, AWS Orga Deployer will determine that it must deploy the IAM role in this new account the next time you execute this package. Example:

```
Modules:
  MyProdIAMRole:
    Deployments:
      - Include:
          OUIds: ou-12345
          Regions: ["eu-west-1", "us-east-1"]
``` 

Hope that helps understand how it works. Let me know if you have any follow-up questions.
